version: "3.9"

services:
  flask_api:
    build:
      context: .
    ports:
      8000:80
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp